### ISSUE TITLE
Image files not deleting

### ISSUE THREAD

**Issue by moboid** [ramiismail/dopresskit#49]
For superhypercube [our year-old presskit()](http://www.superhypercube.com/presskit/) contains some old game screenshots that we need to get rid of because they are inaccurate, and journos are using them for launch.  (panic!)
we deleted all the old images in the folder, but they are still showing up if you load the presskit.  (even with a clean refresh)
is there anything happening on the presskit() side that we need to change?   where are these pulling from?
Is this just an issue with our web hosting, like propagation or somesuch?  (we use Dreamhost)  It's weird to not be able to immediately see changes we make...

**Comment by Dearon** [comment]
It reads images directly from the images directory, so I doubt that it's a issue on the side of Presskit. It might be Dreamhost doing some sort of caching but it's hard to say without more information (I also have no idea which images are the old ones so I can't say if the old ones are showing up for me).

**Comment by moboid** [comment]
Heres one of the images that should show up:
![superhypercube_screenshot_31072016_09](https://cloud.githubusercontent.com/assets/82568/19155045/f94b81ac-8baa-11e6-86fd-6fe5db667d51.jpg)
And here's an article full of the images that should NOT show up:
http://uploadvr.com/superhypercube-review-psvr/

**Comment by moboid** [comment]
And yeah we noticed it was pulling directly from the folder, which is why we were quite confused why a simple image replacement didn't work.  Thanks for your help!  Let me know if/when you see the newer pics!

**Comment by Dearon** [comment]
Yeah that is really odd, if I go directly to the images which shouldn't exist anymore it still loads: http://www.superhypercube.com/presskit/images/SHC_Screenshot_12-16-15_18-50-54.png

So it seems that the images haven't actually been deleted on Dreamhosts end?

**Comment by moboid** [comment]
Figured it out.  it was def server-side.  STUPID USER  ERROR.  (that being me)
